# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0c5e2ed4d0809572d6fc9e23f1970b5b5f49751079d30abf258307a4337bf6da6649ac01f945017193bfa906882a111be005402280824b747328ed0da9fa075

test:
  secret_key_base: 7e0d67e8973751e83d664b33565aa0fb392072c061180429dbef119a3199ae3bf184a35d2eded336cd0fc47b2b2dee6c02d9c01e7be0cd23452157ecbfcfcd3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
